version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    restart: always
    env_file:
      - .env
    volumes:
      - ./docker/rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"