version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    restart: always
    volumes:
      - ./docker/rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  dynamodb-local:
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-rcwa
    hostname: dynamodb
    restart: always
    user: root
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"