spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}

api:
  reddit:
    app_name: ${REDDIT_API_APP_NAME}
    author: ${REDDIT_API_AUTHOR}
    version: ${REDDIT_API_VERSION}
    client_id: ${REDDIT_API_CLIENT_ID}
    client_secret: ${REDDIT_API_CLIENT_SECRET}
