server:
  port: 8080

spring:
  application:
    name: reddit-community-word-analyser
  rabbitmq:
    host: localhost
    port: 5672
    username: XXX
    password: XXX

api:
  reddit:
    app_name: "###"
    author: "###"
    version: "###"
    client_id: "###"
    client_secret: "###"