server:
  port: 8080

spring:
  application:
    name: reddit-community-word-analyser
  banner:
    location: "classpath:/other/banner.txt"

management:
  endpoints:
    web:
      exposure:
        include: health,mappings,metrics,httptrace
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

queue:
  name: reddit_user_text_queue

amazon:
  dynamodb:
    endpoint: http://localhost:8000/
  aws:
    accesskey: XXX
    secretkey: XXX