server:
  port: 8080

spring:
  application:
    name: reddit-community-word-analyser
  rabbitmq:
    host: localhost
    port: 5672
    username: XXX
    password: XXX

api:
  reddit:
    app_name: "community-word-analyser"
    author: "Ticketedmoon"
    version: "1.0.0"
    client_id: "XXX"
    client_secret: "XXX"

queue:
  name: reddit_user_text_queue